### ISSUE TITLE
Question about visualize the parcellation result

### ISSUE THREAD

**Issue by tanjia123456** [EdwardSmith1884/GEOMetrics#19]
Hello, Here I have a question. How should I visualize the results of node classification? Would you mind sharing the source program for visualizing the results of facial segmentation? Thanks a lot

**Comment by EdwardSmith1884** [comment]
Hi, do you mean the visualization you see here: https://arxiv.org/pdf/1901.11461.pdf in figure 5?

**Comment by tanjia123456** [comment]
Yes, it's similar, but I am doing brain segmentation. I want to visualize the results of node classification to see how the segmentation effect is.

**Comment by tanjia123456** [comment]
what's more, I saw you quoted 'convolutional neural networks for mesh-based parcellation of the cerebral cortex'this article, so I’m asking if you know how to visualize and don’t intend to offend

**Comment by EdwardSmith1884** [comment]
No problem , I'm happy to help out. The way I do all visualization in my paper is through Blender . But Blender might be over kill here. I would recommend trimesh for this . Trimesh is used for manipulating meshes, and has a built is visualizer if you want to manually play around with a few models , and a renderer if you want to automatically produce large amounts of visualizations. With respect to your particular problem I would recommend checking out the solutions to this issue here : https://github.com/mikedh/trimesh/issues/526 .

**Comment by tanjia123456** [comment]
ok,thank you very much
